version: '3.3'

services:
  express:
    build: ./api
    image: local/express
    volumes:
      - ./api:/usr/src/app
    restart: always
    ports:
      - 3005:3005
    environment:
      - PORT=3005